# docker-compose.yml
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pcparts
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"